Snow projection discovery
NASA-IMPACT/veda-config pull request #197
Opened 2023-02-10 22:43 UTC by jupflug

Creating a data discovery for the climate and snow projection datasets

*** Please don't merge this pull request to the main branch yet, issuing this pull request for preview purposes internally ***

2023-04-11 09:37 UTC, danielfdsilva requested changes
All the collections used here are missing the `dashboard:time_density` property, which leads to problems. _This is a data situation, not about this configuration_

- https://staging-stac.delta-backend.com/collections/CMIP245-winter-median-pr
- https://staging-stac.delta-backend.com/collections/CMIP585-winter-median-pr
- https://staging-stac.delta-backend.com/collections/CMIP245-winter-median-ta
- https://staging-stac.delta-backend.com/collections/CMIP585-winter-median-ta

cc @anayeaye @smohiudd 

---

@jupflug
- The images are a bit to heavy and should be cropped/compressed. You cant find [guidance in our docs](https://github.com/NASA-IMPACT/veda-config/blob/cf883f64238a63871f76c614faa4063ec74e3b9f/docs/frontmatter/media.md).
- There are several csv files included in this PR that don't seem to be used. Consider removing them if not needed.

2023-04-11 09:37 UTC, danielfdsilva commented on discoveries/projected-changes-WUS-snow.discoveries.mdx
> +<Block type='wide'>
Consider whether to keep the `wide` block for such little text, as it shows up in a partial column looking broken.

<img width="1217" alt="image" src="https://user-images.githubusercontent.com/1090606/231118897-199aac9e-52ad-41c1-b987-64ce44d61b0a.png">

2023-04-11 09:37 UTC, danielfdsilva commented on discoveries/projected-changes-WUS-snow.discoveries.mdx
> +<Block type='wide'>
Consider whether to keep the `wide` block for such little text, as it shows up in a partial column looking broken.

2023-04-11 16:58 UTC, danielfdsilva commented
@ividito This sort of works but so far for yearly datasets the date was set at the beginning of the year (jan 1st) since on time step represent the whole year. In this case it is set to feb 14th, and it breaks things a bit.
Is this something to be expected: yearly datasets that fall on specific days? Can the dates be changed?

2023-04-12 12:58 UTC, danielfdsilva commented on discoveries/projected-changes-WUS-snow.discoveries.mdx
> +<Block type='wide'>
@jupflug Should this block be wide (last in the page)

<img width="1220" alt="image" src="https://user-images.githubusercontent.com/1090606/231464730-c9d70482-077c-4c77-853e-d643aa42255c.png">

2023-04-12 14:01 UTC, jupflug commented
Sorry @danielfdsilva. I'm not sure how I missed the two of those. The newest push should have the reduced jpgs (both around 300 KB).

2023-04-13 09:10 UTC, merged